<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_charts"
 *
 * Auto generated by SAV Library Kickstarter 14-02-23
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Charts',
    'description' => 'Extension which displays charts using the charts.js library',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '11.5.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.28-11.5.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
