<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_charts"
 *
 * Auto generated by SAV Library Kickstarter 22-01-24
 *
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Charts',
    'description' => 'Extension which displays charts using the chart.js library',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '13.4.0',
    'constraints' => [
        'depends' => [
            'typo3' => '12.4.6-13.4.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];